### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by ShubhamBhut** [NeuralNine/stock-visualizer#1]
I am getting this error when using stock visualizer. I believe it's due to the change in yfinance api in recent years. Full error text
```Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/kailorston/my_work/QuantFinance/stocks-viewer.py", line 25, i
n visualize
    data = web.DataReader(ticker, 'yahoo', start, end)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kailorston/.local/lib/python3.11/site-packages/pandas/util/_d
ecorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kailorston/.local/lib/python3.11/site-packages/pandas_datarea
der/data.py", line 379, in DataReader
    ).read()
      ^^^^^^
  File "/home/kailorston/.local/lib/python3.11/site-packages/pandas_datarea
der/base.py", line 253, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols
))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
  File "/home/kailorston/.local/lib/python3.11/site-packages/pandas_datarea
der/yahoo/daily.py", line 153, in _read_one_data
    data = j["context"]["dispatcher"]["stores"]["HistoricalPriceStore"]
```

**Comment by ShubhamBhut** [comment]
Can be fixed with my PR.
